
task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 4
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:\AI\Datasets\20250731-ppe2286y\train\images
    ann_file: D:\AI\Datasets\20250731-ppe2286y\train\_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: [4, 36, 64]
        ops: ['Mosaic', 'RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
      mosaic_prob: 0.5
  shuffle: True
  num_workers: 8
  drop_last: True
  total_batch_size: 8
  collate_fn:
    type: BatchImageCollateFunction
    mixup_prob: 0.5
    mixup_epochs: [4, 36]
    copyblend_prob: 0.5
    copyblend_epochs: [4, 64]
    stop_epoch: 64
    area_threshold: 100
    num_objects: 3
    with_expand: True
    expand_ratios: [0.1, 0.25]
    ema_restart_decay: 0.9998
    base_size: 640
    base_size_repeat: 3

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: D:\AI\Datasets\20250731-ppe2286y\valid\images
    ann_file: D:\AI\Datasets\20250731-ppe2286y\valid\_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  num_workers: 8
  drop_last: False
  total_batch_size: 8
  collate_fn:
    type: BatchImageCollateFunction
